# Generated by Django 2.2.17 on 2021-02-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210217_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='adj_close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='bookmarked',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='high',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='low',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
    ]
