# Generated by Django 2.2.9 on 2021-01-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
