# Generated by Django 2.2.9 on 2021-01-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(max_length=20),
        ),
    ]
