# Generated by Django 2.2.9 on 2021-01-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210130_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
