# Generated by Django 2.2.9 on 2021-01-31 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20210130_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='before_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='bookmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked', to=settings.AUTH_USER_MODEL),
        ),
    ]
