# Generated by Django 2.2.9 on 2021-02-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210131_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='stock',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='chart_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='stock',
            name='decrease',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='increase',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
