# Generated by Django 2.2.9 on 2021-02-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20210202_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='today_date',
        ),
    ]
