# Generated by Django 2.2.9 on 2021-02-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_stock_today_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fluctuation_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
