# Generated by Django 2.2.17 on 2021-02-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_auto_20210208_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail_alarm_time_hour',
            field=models.IntegerField(choices=[(9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], null=True, verbose_name='시'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail_alarm_time_minute',
            field=models.IntegerField(choices=[(0, '0'), (10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50')], null=True, verbose_name='분'),
        ),
    ]
